// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"ucenter-api/internal/middleware"

	"ucenter-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	addRegisterRouters(server, serverCtx)
	addLoginRouters(server, serverCtx)
	addWalletRouters(server, serverCtx)
	addWithdrawRouters(server, serverCtx)
	addSecurityRouters(server, serverCtx)
}

// 注册相关
func addRegisterRouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/uc/register/phone",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uc/mobile/code",
				Handler: SendCodeHandler(serverCtx),
			},
		},
	)
}

// 登录相关
func addLoginRouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/uc/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uc/check/login",
				Handler: CheckLoginHandler(serverCtx),
			},
		},
	)
}

// 钱包
func addWalletRouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	routers := []rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/uc/asset/wallet/:coinName",
			Handler: GetWalletWithCoin(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/uc/asset/wallet",
			Handler: GetWallet(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/uc/asset/wallet/reset-address",
			Handler: ResetWalletAddress(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/uc/asset/transaction/all",
			Handler: GetAllTransactions(serverCtx),
		},
	}
	server.AddRoutes(
		rest.WithMiddleware(middleware.Auth(serverCtx.Config.Jwt.AccessSecret), routers...),
	)
}

// 提现
func addWithdrawRouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	routers := []rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/uc/withdraw/support/coin/info",
			Handler: GetSupportedCoinInfo(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/uc/mobile/withdraw/code",
			Handler: SendCode(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/uc/withdraw/apply/code",
			Handler: Withdraw(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/uc/withdraw/record",
			Handler: Record(serverCtx),
		},
	}
	server.AddRoutes(
		rest.WithMiddleware(middleware.Auth(serverCtx.Config.Jwt.AccessSecret), routers...),
	)
}

// 安全
func addSecurityRouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	routers := []rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/uc/approve/security/setting",
			Handler: SecuritySetting(serverCtx),
		},
	}
	server.AddRoutes(
		rest.WithMiddleware(middleware.Auth(serverCtx.Config.Jwt.AccessSecret), routers...),
	)
}