// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"
	"grpc-common/ucenter/types/user"

	"ucenter-rpc/internal/logic"
	"ucenter-rpc/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}


func (s *UserServer) FindUserById(ctx context.Context, in *user.UserRequest) (*user.UserInfoResp, error) {
	l := logic.NewUserLogic(ctx, s.svcCtx)
	return l.FindUserById(in)
}
