// Code generated by goctl. DO NOT EDIT.
// Source: wallet.proto

package server

import (
	"context"
	"grpc-common/ucenter/types/withdraw"

	"ucenter-rpc/internal/logic"
	"ucenter-rpc/internal/svc"
)

type WithdrawServer struct {
	svcCtx *svc.ServiceContext
	withdraw.UnimplementedWithdrawServer
}

func NewWithdrawServer(svcCtx *svc.ServiceContext) *WithdrawServer {
	return &WithdrawServer{
		svcCtx: svcCtx,
	}
}


func (s *WithdrawServer) FindAddressesByCoinId(ctx context.Context, in *withdraw.WithdrawRequest) (*withdraw.AddressSimpleList, error) {
	l := logic.NewWithdrawLogic(ctx, s.svcCtx)
	return l.FindAddressesByCoinId(in)
}

func (s *WithdrawServer) SendCode(ctx context.Context, in *withdraw.SendCodeReq) (*withdraw.EmptyResp, error) {
	l := logic.NewWithdrawLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

func (s *WithdrawServer) Withdraw(ctx context.Context, in *withdraw.WithdrawRequest) (*withdraw.EmptyResp, error) {
	l := logic.NewWithdrawLogic(ctx, s.svcCtx)
	return l.Withdraw(in)
}

func (s *WithdrawServer) WithdrawRecord(ctx context.Context, in *withdraw.WithdrawRequest) (*withdraw.RecordList, error) {
	l := logic.NewWithdrawLogic(ctx, s.svcCtx)
	return l.WithdrawRecord(in)
}



