// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: withdraw.proto

package withdraw

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Withdraw_FindAddressesByCoinId_FullMethodName = "/withdraw.Withdraw/FindAddressesByCoinId"
	Withdraw_SendCode_FullMethodName              = "/withdraw.Withdraw/SendCode"
	Withdraw_Withdraw_FullMethodName              = "/withdraw.Withdraw/Withdraw"
	Withdraw_WithdrawRecord_FullMethodName        = "/withdraw.Withdraw/WithdrawRecord"
)

// WithdrawClient is the client API for Withdraw service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WithdrawClient interface {
	FindAddressesByCoinId(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*AddressSimpleList, error)
	SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*EmptyResp, error)
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*EmptyResp, error)
	WithdrawRecord(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*RecordList, error)
}

type withdrawClient struct {
	cc grpc.ClientConnInterface
}

func NewWithdrawClient(cc grpc.ClientConnInterface) WithdrawClient {
	return &withdrawClient{cc}
}

func (c *withdrawClient) FindAddressesByCoinId(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*AddressSimpleList, error) {
	out := new(AddressSimpleList)
	err := c.cc.Invoke(ctx, Withdraw_FindAddressesByCoinId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawClient) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Withdraw_SendCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*EmptyResp, error) {
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Withdraw_Withdraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawClient) WithdrawRecord(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*RecordList, error) {
	out := new(RecordList)
	err := c.cc.Invoke(ctx, Withdraw_WithdrawRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithdrawServer is the server API for Withdraw service.
// All implementations must embed UnimplementedWithdrawServer
// for forward compatibility
type WithdrawServer interface {
	FindAddressesByCoinId(context.Context, *WithdrawRequest) (*AddressSimpleList, error)
	SendCode(context.Context, *SendCodeReq) (*EmptyResp, error)
	Withdraw(context.Context, *WithdrawRequest) (*EmptyResp, error)
	WithdrawRecord(context.Context, *WithdrawRequest) (*RecordList, error)
	mustEmbedUnimplementedWithdrawServer()
}

// UnimplementedWithdrawServer must be embedded to have forward compatible implementations.
type UnimplementedWithdrawServer struct {
}

func (UnimplementedWithdrawServer) FindAddressesByCoinId(context.Context, *WithdrawRequest) (*AddressSimpleList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAddressesByCoinId not implemented")
}
func (UnimplementedWithdrawServer) SendCode(context.Context, *SendCodeReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCode not implemented")
}
func (UnimplementedWithdrawServer) Withdraw(context.Context, *WithdrawRequest) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (UnimplementedWithdrawServer) WithdrawRecord(context.Context, *WithdrawRequest) (*RecordList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawRecord not implemented")
}
func (UnimplementedWithdrawServer) mustEmbedUnimplementedWithdrawServer() {}

// UnsafeWithdrawServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WithdrawServer will
// result in compilation errors.
type UnsafeWithdrawServer interface {
	mustEmbedUnimplementedWithdrawServer()
}

func RegisterWithdrawServer(s grpc.ServiceRegistrar, srv WithdrawServer) {
	s.RegisterService(&Withdraw_ServiceDesc, srv)
}

func _Withdraw_FindAddressesByCoinId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServer).FindAddressesByCoinId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Withdraw_FindAddressesByCoinId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServer).FindAddressesByCoinId(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Withdraw_SendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServer).SendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Withdraw_SendCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServer).SendCode(ctx, req.(*SendCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Withdraw_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Withdraw_Withdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Withdraw_WithdrawRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServer).WithdrawRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Withdraw_WithdrawRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServer).WithdrawRecord(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Withdraw_ServiceDesc is the grpc.ServiceDesc for Withdraw service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Withdraw_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "withdraw.Withdraw",
	HandlerType: (*WithdrawServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAddressesByCoinId",
			Handler:    _Withdraw_FindAddressesByCoinId_Handler,
		},
		{
			MethodName: "SendCode",
			Handler:    _Withdraw_SendCode_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _Withdraw_Withdraw_Handler,
		},
		{
			MethodName: "WithdrawRecord",
			Handler:    _Withdraw_WithdrawRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "withdraw.proto",
}
