// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"exchange-api/internal/handler/order"
	"exchange-api/internal/middleware"
	"exchange-api/internal/svc"
	"github.com/zeromicro/go-zero/rest"
	"net/http"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	addOrderRouters(server, serverCtx)
}

func addOrderRouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	rs := []rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/exchange/order/history",
			Handler: order.GetHistoryOrders(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/exchange/order/current",
			Handler: order.GetCurrentOrders(serverCtx),
		},
		{
			Method: http.MethodPost,
			Path: "/exchange/order/add",
			Handler: order.AddOrder(serverCtx),
		},
	}
	server.AddRoutes(rest.WithMiddleware(middleware.Auth(serverCtx.Config.Jwt.AccessSecret), rs...))
}

