// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"
	"github.com/shopspring/decimal"
	"grpc-common/trade-engine/types/match"
	"trade-engine/internal/engine"
	"trade-engine/internal/model"
	"trade-engine/internal/svc"
)

type TradeEngineServer struct {
	svcCtx     *svc.ServiceContext
	tradePools *engine.TradePools
	match.UnimplementedMatchServiceServer
}

func NewTradeEngineServer(svcCtx *svc.ServiceContext) *TradeEngineServer {
	server := &TradeEngineServer{
		svcCtx: svcCtx,
	}
	server.init()
	return server
}

func (tes *TradeEngineServer) init() {
	// TODO 查有几个交易对
	tradePairs := []string{"BTC/USDT", "ETH/USDT"}
	tradePools, err := engine.NewTradePools(tradePairs, tes.svcCtx.KCli)
	if err != nil {
		panic(err)
		return
	}
	tes.tradePools = tradePools
}

func (tes *TradeEngineServer) AddOrder(ctx context.Context, in *match.AddOrderRequest) (*match.AddOrderResponse, error) {
	price, err := decimal.NewFromString(in.Order.Price)
	if err != nil {
		return &match.AddOrderResponse{
			Code: -1,
			Msg:  "price err",
		}, err
	}
	quantity, err := decimal.NewFromString(in.Order.Quantity)
	if err != nil {
		return &match.AddOrderResponse{
			Code: -1,
			Msg:  "quantity err",
		}, err
	}

	order := &model.Order{
		Id:        in.Order.Id,
		Uid:       in.Order.Uid,
		TradePair: in.Order.TradePair,
		Price:     price,
		Quantity:  quantity,
		Side:      model.Side(in.Order.Side),
		Type:      model.Type(in.Order.Type),
	}
	err = tes.tradePools.AddOrder(order)
	if err != nil {
		return &match.AddOrderResponse{
			Code: -1,
			Msg: err.Error(),
		}, err
	}
	return &match.AddOrderResponse{
		Code: 0,
		Msg: "success",
	}, nil
}

func (tes *TradeEngineServer) CancelOrder(ctx context.Context, cancelOrderRequest *match.CancelOrderRequest) (*match.CancelOrderResponse, error) {
	return nil, nil
}
