// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"market-api/internal/handler/exchange_rate"
	"market-api/internal/handler/market"
	"market-api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	addExchangeRateRouters(server, serverCtx)
	addMarketRouters(server, serverCtx)
	addSocketIORouters(server, serverCtx)
}

func addExchangeRateRouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/market/exchange-rate/usd/:unit",
				Handler: exchange_rate.ExchangeRateHandler(serverCtx),
			},
		},
	)
}

func addMarketRouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/market/symbol-thumb-trend",
				Handler: market.SymbolThumbTrendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/market/symbol-thumb",
				Handler: market.SymbolThumbHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/market/symbol-info",
				Handler: market.SymbolInfoHandler(serverCtx),  // 获取交易币详情
			},
			{
				Method:  http.MethodPost,
				Path:    "/market/coin-info",
				Handler: market.CoinInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/market/history",
				Handler: market.HistoryHandler(serverCtx),
			},
		},
	)
}

func addSocketIORouters(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/socket.io",
				Handler: nil,
			},
			{
				Method:  http.MethodGet,
				Path:    "/socket.io",  // nginx配置
				Handler: nil,
			},
		},
	)
}
